### ISSUE TITLE
Fix duplicate `alias` in configuration.

### ISSUE THREAD

**Issue by Plommonsorbet** [pier-cli/pier#61]
Currently the config has a duplicate definition of the script alias, would be nice to remove one of them. Will probably require a bit of code shuffling to make work though.

```toml
[scripts.this-is-the-alias]
alias = 'this-is-the-alias'
command = '''
#!/bin/sh
echo "Hello $1, my name is $2. -- script $0"
'''
```
