### ISSUE TITLE
Attempting to run `pier list` segfaults straight away

### ISSUE THREAD

**Issue by MostHated** [pier-cli/pier#94]
Hello,
  Unfortunately, when I attempt to run `pier list` it simply segfaults:

```zsh
zsh ❯ pier list
[1]    503177 segmentation fault (core dumped)  pier list

```

From syslog:

```log
2024-01-20T10:45:50.051578-06:00 mosthated-pc kernel: [ 3786.184976] pier[503177]: segfault at 89 ip 0000561acae62840 sp 00007ffd0699a570 error 4 in pier[561acae22000+ea000] likely on CPU 19 (core 3, socket 0)
2024-01-20T10:45:50.051588-06:00 mosthated-pc kernel: [ 3786.184985] Code: 73 08 31 c9 45 31 d2 eb 46 90 49 89 d0 49 83 e0 fc 4c 8d 8e 10 01 00 00 31 c9 45 31 d2 66 66 66 66 2e 0f 1f 84 00 00 00 00 00 <49> 03 89 28 ff ff ff 49 03 89 70 ff ff ff 49 03 49 b8 49 03 09 49
```

I only just installed it and attempted to run `pier config-init` then was trying other commands, one being `list` which lead the the segfault.

I checked my config and there was not an interpreter, so I set it and my config looks like this:

```toml
[scripts.hello-pier]
alias = 'hello-pier'
command = 'echo Hello, Pier!'
description = 'This is an example command.'

[default]
interpreter = ["/bin/bash", "-c"]
```

<details>
<summary>System Details</summary>

```
OS: Ubuntu 23.10 x86_64
Host: X670E Taichi
Kernel: 6.5.0-14-generic
Uptime: 1 hour, 9 mins
Packages: 3591 (dpkg), 73 (flatpak), 27 (snap)
Shell: zsh 5.9
Resolution: 2560x1080
DE: GNOME 45.2
WM: Mutter
WM Theme: Adwaita
Theme: Yaru-dark [GTK2/3]
Icons: Yaru [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 7950X (32) @ 5.881GHz
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
GPU: AMD ATI 5a:00.0 Raphael
Memory: 13501MiB / 63398MiB
```

</details>
